services:

  # Main dispatcher and SSL manager
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: always
    environment:
      TZ: "Europe/Moscow"
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm-data/data:/data
      - ./npm-data/letsencrypt:/etc/letsencrypt

  # PostgreSQL DB
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro # Автоматическое создание таблиц
    restart: always
    # Check DB is ready (Healthcheck)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # REST API application
  node_app:
    image: node:18-alpine
    container_name: rest_api
    working_dir: /app
    init: true # <--- IMPORTANT: Enables correct forwarding of PID 1 signals
    stop_grace_period: 30s
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      FIREBASE_SERVICE_ACCOUNT: ${FIREBASE_SERVICE_ACCOUNT}
#      FIREBASE_SERVICE_FILE: ${FIREBASE_SERVICE_FILE}
    volumes:
      - .:/app                                                                                                   # Source code synchronization
      - /app/node_modules                                                                                        # Isolating the dependencies folder inside Docker
#      - ../geofences-chat-app-firebase-adminsdk-fbsvc.json:/app/geofences-chat-app-firebase-adminsdk-fbsvc.json # FIREBASE_SERVICE_FILE mode
    # Installing nodemon on the fly and running in change-monitoring mode
#    command: sh -c "npm install && npm install -g nodemon && nodemon index.js"
    # Running through npx (to avoid clogging the global cache).
    # Pass the --passthrough-signals flag, and run index.js as an array.
    #! Run 'docker compose exec node_app npm install' once when package.json changes.
    command: sh -c "npm install && exec npx nodemon index.js" # npx nodemon index.js  # npx nodemon --passthrough-signals index.js
    # API starts after Postgres DB is ready
    depends_on:
      postgres:
        condition: service_healthy

  # Postgres DB WEB console
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin_web
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data:
